version: '3.3'

services:
  api:
    container_name: api
    build: api/
    volumes:
      - $HOME/.shuffle/networks/localhost/accounts/latest:/shuffle
    environment:
      - PYTHONUNBUFFERED=1
      - APP_BASE_URL=http://localhost:3000
