Command `sandbox publish --test -p ../../`:
Command `sandbox run --test -p ../../ scripts/initialize/initialize_error_no_coin_a.move --signers 0x3 0x4`:
Execution aborted with code 1 in module 00000000000000000000000000000002::Exchange.
Command `sandbox run --test -p ../../ scripts/initialize/initialize_error_not_enough_coin_a.move --signers 0x3 0x4`:
Execution aborted with code 2 in module 00000000000000000000000000000002::Exchange.
Command `sandbox run --test -p ../../ scripts/initialize/initialize_error_no_coin_b.move --signers 0x3 0x4`:
Execution aborted with code 1 in module 00000000000000000000000000000002::Exchange.
Command `sandbox run --test -p ../../ scripts/initialize/initialize_error_not_enough_coin_b.move --signers 0x3 0x4`:
Execution aborted with code 2 in module 00000000000000000000000000000002::Exchange.
Command `sandbox run --test -p ../../ scripts/initialize/initialize_success.move -v --signers 0x3 0x4`:
Changed resource(s) under 2 address(es):
  Changed 3 resource(s) under address 00000000000000000000000000000003:
    Added type 0x2::CoinA::CoinA: [244, 1, 0, 0, 0, 0, 0, 0] (wrote 38 bytes)
      drop store key 0x2::CoinA::CoinA {
          value: 500
      }
    Added type 0x2::CoinB::CoinB: [136, 19, 0, 0, 0, 0, 0, 0] (wrote 38 bytes)
      drop store key 0x2::CoinB::CoinB {
          value: 5000
      }
    Added type 0x2::Exchange::Exchange: [244, 1, 0, 0, 0, 0, 0, 0, 136, 19, 0, 0, 0, 0, 0, 0, 244, 1, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 0, 0, 0, 0] (wrote 68 bytes)
      store key 0x2::Exchange::Exchange {
          coin_a: 500
          coin_b: 5000
          LP_minted: 500
          comm_rate: 30
      }
  Changed 1 resource(s) under address 00000000000000000000000000000004:
    Added type 0x2::Exchange::LPCoin: [244, 1, 0, 0, 0, 0, 0, 0] (wrote 42 bytes)
      drop store key 0x2::Exchange::LPCoin {
          value: 500
      }
Wrote 186 bytes of resource ID's and data
Command `sandbox run --test -p ../../ scripts/exists_at/exists_at.move --signers 0x3`:
[debug] true
Command `sandbox run --test -p ../../ scripts/get_CoinA_in_pool/get_CoinA_in_pool.move --signers 0x3`:
[debug] 500
Command `sandbox run --test -p ../../ scripts/get_CoinB_in_pool/get_CoinB_in_pool.move --signers 0x3`:
[debug] 5000
Command `sandbox run --test -p ../../ scripts/get_minted_LPCoin/get_minted_LPCoin.move --signers 0x3`:
[debug] 500
Command `sandbox run --test -p ../../ scripts/add_liquidity/add_liquidity_success.move -v --signers 0x3 0x4`:
Changed resource(s) under 2 address(es):
  Changed 3 resource(s) under address 00000000000000000000000000000003:
    Changed type 0x2::CoinA::CoinA: [232, 3, 0, 0, 0, 0, 0, 0] (wrote 38 bytes)
         drop store key 0x2::CoinA::CoinA {
-            value: 500
+            value: 1000
         }
    Changed type 0x2::CoinB::CoinB: [16, 39, 0, 0, 0, 0, 0, 0] (wrote 38 bytes)
         drop store key 0x2::CoinB::CoinB {
-            value: 5000
+            value: 10000
         }
    Changed type 0x2::Exchange::Exchange: [232, 3, 0, 0, 0, 0, 0, 0, 16, 39, 0, 0, 0, 0, 0, 0, 232, 3, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 0, 0, 0, 0] (wrote 68 bytes)
         store key 0x2::Exchange::Exchange {
-            coin_a: 500
-            coin_b: 5000
-            LP_minted: 500
+            coin_a: 1000
+            coin_b: 10000
+            LP_minted: 1000
             comm_rate: 30
         }
  Changed 1 resource(s) under address 00000000000000000000000000000004:
    Changed type 0x2::Exchange::LPCoin: [232, 3, 0, 0, 0, 0, 0, 0] (wrote 42 bytes)
         drop store key 0x2::Exchange::LPCoin {
-            value: 500
+            value: 1000
         }
Wrote 186 bytes of resource ID's and data
Command `sandbox run --test -p ../../ scripts/remove_liquidity/remove_liquidity_success.move -v --signers 0x3 0x4`:
Changed resource(s) under 2 address(es):
  Changed 3 resource(s) under address 00000000000000000000000000000003:
    Changed type 0x2::CoinA::CoinA: [244, 1, 0, 0, 0, 0, 0, 0] (wrote 38 bytes)
         drop store key 0x2::CoinA::CoinA {
-            value: 1000
+            value: 500
         }
    Changed type 0x2::CoinB::CoinB: [136, 19, 0, 0, 0, 0, 0, 0] (wrote 38 bytes)
         drop store key 0x2::CoinB::CoinB {
-            value: 10000
+            value: 5000
         }
    Changed type 0x2::Exchange::Exchange: [244, 1, 0, 0, 0, 0, 0, 0, 136, 19, 0, 0, 0, 0, 0, 0, 244, 1, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 0, 0, 0, 0] (wrote 68 bytes)
         store key 0x2::Exchange::Exchange {
-            coin_a: 1000
-            coin_b: 10000
-            LP_minted: 1000
+            coin_a: 500
+            coin_b: 5000
+            LP_minted: 500
             comm_rate: 30
         }
  Changed 1 resource(s) under address 00000000000000000000000000000004:
    Changed type 0x2::Exchange::LPCoin: [244, 1, 0, 0, 0, 0, 0, 0] (wrote 42 bytes)
         drop store key 0x2::Exchange::LPCoin {
-            value: 1000
+            value: 500
         }
Wrote 186 bytes of resource ID's and data
Command `sandbox run --test -p ../../ scripts/swap_coinA_to_coinB/swap_coinA_to_coinB_success.move -v --signers 0x3 0x4`:
Changed resource(s) under 1 address(es):
  Changed 3 resource(s) under address 00000000000000000000000000000003:
    Changed type 0x2::CoinA::CoinA: [88, 2, 0, 0, 0, 0, 0, 0] (wrote 38 bytes)
         drop store key 0x2::CoinA::CoinA {
-            value: 500
+            value: 600
         }
    Changed type 0x2::CoinB::CoinB: [73, 16, 0, 0, 0, 0, 0, 0] (wrote 38 bytes)
         drop store key 0x2::CoinB::CoinB {
-            value: 5000
+            value: 4169
         }
    Changed type 0x2::Exchange::Exchange: [88, 2, 0, 0, 0, 0, 0, 0, 73, 16, 0, 0, 0, 0, 0, 0, 244, 1, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 0, 0, 0, 0] (wrote 68 bytes)
         store key 0x2::Exchange::Exchange {
-            coin_a: 500
-            coin_b: 5000
+            coin_a: 600
+            coin_b: 4169
             LP_minted: 500
             comm_rate: 30
         }
Wrote 144 bytes of resource ID's and data
Command `sandbox run --test -p ../../ scripts/swap_coinB_to_coinA/swap_coinB_to_coinA_success.move -v --signers 0x3 0x4`:
Changed resource(s) under 1 address(es):
  Changed 3 resource(s) under address 00000000000000000000000000000003:
    Changed type 0x2::CoinA::CoinA: [229, 1, 0, 0, 0, 0, 0, 0] (wrote 38 bytes)
         drop store key 0x2::CoinA::CoinA {
-            value: 600
+            value: 485
         }
    Changed type 0x2::CoinB::CoinB: [49, 20, 0, 0, 0, 0, 0, 0] (wrote 38 bytes)
         drop store key 0x2::CoinB::CoinB {
-            value: 4169
+            value: 5169
         }
    Changed type 0x2::Exchange::Exchange: [229, 1, 0, 0, 0, 0, 0, 0, 49, 20, 0, 0, 0, 0, 0, 0, 244, 1, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 0, 0, 0, 0] (wrote 68 bytes)
         store key 0x2::Exchange::Exchange {
-            coin_a: 600
-            coin_b: 4169
+            coin_a: 485
+            coin_b: 5169
             LP_minted: 500
             comm_rate: 30
         }
Wrote 144 bytes of resource ID's and data
